# Generated by Django 4.2b1 on 2023-02-27 20:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('casher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categoryID',
            new_name='product_category_id',
        ),
        migrations.RenameField(
            model_name='receipt_item',
            old_name='product_id',
            new_name='item_product_id',
        ),
        migrations.RenameField(
            model_name='receipt_item',
            old_name='receipt_id',
            new_name='item_receipt_id',
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('stock_price', models.FloatField()),
                ('remain_notif', models.IntegerField()),
                ('remain', models.IntegerField()),
                ('stock_category_id', models.OneToOneField(on_delete=models.SET('Coffee'), to='casher.category')),
                ('stock_product_id', models.OneToOneField(on_delete=models.SET('Deleted'), to='casher.product')),
            ],
            options={
                'db_table': 'Stock',
            },
        ),
        migrations.AddField(
            model_name='receipt_item',
            name='item_stock_id',
            field=models.ForeignKey(on_delete=models.SET('Deleted'), to='casher.stock'),
            preserve_default=False,
        ),
    ]
