# Generated by Django 4.1.5 on 2023-03-13 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casher', '0002_alter_category_id_alter_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='CategoryID',
            new_name='CategoryIDs',
        ),
    ]
