# Generated by Django 4.2b1 on 2023-02-27 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casher', '0002_rename_categoryid_product_product_category_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_category_id',
            new_name='CategoryID',
        ),
    ]
