# Generated by Django 4.2b1 on 2023-02-27 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casher', '0003_rename_product_category_id_product_categoryid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt_item',
            old_name='item_product_id',
            new_name='ite_product_ID',
        ),
    ]
