# Generated by Django 4.2b1 on 2023-02-27 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casher', '0004_rename_item_product_id_receipt_item_ite_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt_item',
            old_name='ite_product_ID',
            new_name='item_product_Id',
        ),
    ]
